more robust eqwalizer_specs for OSS
Summary:
When running eqwalizer against OTP sources (without any extra settings/tweaks), it *MAY* fail to parse eqwalizer_specs
because (if the app `public_key` was not built during OTP build).

```
error: parse_error
   ┌─ /Users/me/Library/Caches/elp/eqwalizer_support/src/eqwalizer_specs.erl:15:1
   │
15 │
   │ ^ Issue in included file

error: parse_error
    ┌─ /Users/me/Library/Caches/elp/eqwalizer_support/src/eqwalizer_specs.erl:645:26
    │
645 │     (binary(), plain) -> #'Certificate'{};
    │                          ^^^^^^^^^^^^^^^^ record 'Certificate' undefined
```

----

```
-include_lib("public_key/include/public_key.hrl").
```

it's needed only for one spec - `public_key:pkix_decode_cert`.

Removing that spec from eqwalizer_specs for now to make integration with OTP builds easier (and more debuggable).

(We can revisit it later).

 ---

Rationale:

Loading of eqwalier_specs is crucial and should be robust as much as possible. Consider also the case if eqwalizer is run with Erlang installation that doesn't have `public_key` app for some reason. - It should not fails

Reviewed By: michalmuskala, alanz

Differential Revision: D71797531

fbshipit-source-id: 31cfe550fc0abf06c76669b2a597f0e4e37088ce